intel_robot: 
  diff_drive_controller:
   type: "diff_drive_controller/DiffDriveController"
   publish_rate: 100

   left_wheel: ['scooter_left_wheel_joint']
   right_wheel: ['scooter_right_wheel_joint']

   wheel_radius: 0.05
   wheel_separation: 0.32378
   pose_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 1000.0]
   twist_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 1000.0]
   base_frame_id: base_link

   linear:
      x:
         has_velocity_limits    : true
         max_velocity           : 2.5 # m/s
         min_velocity           : -2.5 # m/s
         has_acceleration_limits: true
         max_acceleration       : 1 # m/s^2
         min_acceleration       : -1 # m/s^2
         


   angular:
      z:
         has_velocity_limits    : true
         max_velocity           : 1  # rad/s
         has_acceleration_limits: true
         max_acceleration       : 1  # rad/s^2
         has_jerk_limits        : true
         max_jerk               : 1  # rad/s^3

     

  
